# These are supported funding model platforms

github: # [taaylormoon, ttayllormoon]
patreon: # [ttayllormoon]
open_collective: # Replace with a single Open Collective username
paypal: # ttayllormoon@icloud.com
cash app: # ttayllormoon@gmail.com
